server {
    listen 80;
    server_name cx.incomify.com;

    client_max_body_size 100m;

    location ^~ /aisoft/deploy/ {
        alias /home/incomify/workspace/deploy/;
        index index.html;
        autoindex off;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://127.0.0.1:3021;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
    }
}
